src/main/java/com/project/echoproject/controller/MallController.java
src/main/resources/templates/mall.html

mall 파일 두개 추가

---

src/main/java/com/project/echoproject/controller/DashboardController.java
src/main/java/com/project/echoproject/entity/UseAmount.java
src/main/resources/templates/dashboard.html

hgy database 생성 및 대쉬보드 페이지 틀 제작

---

src/main/java/com/project/echoproject/controller/NoticeController.java
src/main/java/com/project/echoproject/entity/Notice.java
src/main/java/com/project/echoproject/repository/NoticeRepository.java
src/main/resources/templates/notice_list.html

초기작성.
- Notice 엔티티 생성
- NoticeRepository 생성
- NoticeController 생성
- notice_list.html 생성
한번 확인해주세용!

hw_0621_공지사항 list 화면 만들기

---

src/main/java/com/project/echoproject/entity/Coupon.java
src/main/java/com/project/echoproject/entity/Point.java

쿠폰,포인트 테이블 엔티티 추가

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/entity/Coupon.java
src/main/resources/templates/mall.html

selectCouponDTO 해결해야하는 부분

---

src/main/java/com/project/echoproject/controller/MallController.java

컨트롤러 내용 비웠음

---

src/main/java/com/project/echoproject/entity/SiteUser.java

currentPoint 컬럼 추가

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/dto/CouponDTO.java
src/main/resources/templates/buy.html

1. siteUser 테이블 currentPoint 12000으로 update
2. insert into coupon (coupon_point, coupon_name) values (5000,'스타벅스 오천원 교환권'),(10000,'배달의민족 만원 교환권');
3. localhost:8080/mall 접속 후 구매하기 클릭 
localhost:8080/mall/buy 페이지 캡쳐해서 보내주시면 감사하겠습니다!!

buy페이지, mall컨트톨러,쿠폰 dto

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/dto/CouponDTO.java
src/main/java/com/project/echoproject/service/SiteUserService.java
src/main/java/com/project/echoproject/service/SiteUserServiceImpl.java
src/main/resources/templates/buy.html
src/main/resources/templates/error/payment_failed.html
src/main/resources/templates/pay.html

1. SiteUser테이블에 currentPoint 컬럼 0일때 결제 실패 페이지 떠야함
2. SiteUser테이블에 currentPoint 컬럼 12000일때 스벅쿠폰 구매 시 결제완료 7000 나와야함
currentPoint 값 update해서 테스트 부탁드리겠습니담

SiteUser서비스 추가,결제하기 추가

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/entity/UserCoupon.java
src/main/java/com/project/echoproject/repository/UserCouponRepository.java
src/main/java/com/project/echoproject/service/UserCouponService.java
src/main/resources/templates/error/payment_failed.html
src/main/resources/templates/pay.html

localhost:8080/mall 접속
구매하기 클릭
userCoupon 테이블에 insert 됐는지 확인

쿠폰내역 업데이트 추가

---

src/main/java/com/project/echoproject/controller/MallController.java

테스트방법은 첫번쨰 요청 참고해주세용 
아니면 카톡으로 물어보셔요~

결제하기 클릭 - userCoupon 테이블 insert

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/repository/PointRepository.java
src/main/java/com/project/echoproject/service/PointService.java

결제하기 클릭하면
userCoupon, Point 테이블 insert 됩니당

결제하기 클릭 - point 테이블 insert

---

src/main/java/com/project/echoproject/dto/ChallengeDTO.java

챌린지 dto 추가

---

src/main/java/com/project/echoproject/entity/Challenge.java

챌린지 테이블 수정

---

src/main/java/com/project/echoproject/service/ChallengeService.java
src/main/resources/templates/challenge.html

챌린지 현황 페이지 수정

---

src/main/java/com/project/echoproject/controller/ChallengeController.java
src/main/java/com/project/echoproject/entity/Challenge.java
src/main/java/com/project/echoproject/service/ChallengeService.java
src/main/resources/templates/challengeAdd.html

챌린지 등록 페이지

---

src/main/java/com/project/echoproject/controller/ChallengeController.java
src/main/resources/templates/buy.html
src/main/resources/templates/challenge.html
src/main/resources/templates/challengeAdd.html
src/main/resources/templates/layout.html
src/main/resources/templates/mall.html

챌린지 종류 추가, 결제 alert 창 추가

---

src/main/java/com/project/echoproject/controller/MallController.java
src/main/java/com/project/echoproject/entity/Point.java
src/main/resources/templates/layout.html

포인트 날짜 추가, 메뉴 클릭

---

.idea/dataSources.xml
src/main/java/com/project/echoproject/controller/MallController.java
src/main/resources/templates/buy.html
src/main/resources/templates/error/payment_failed.html
src/main/resources/templates/hl.html
src/main/resources/templates/mall.html
src/main/resources/templates/pay.html

mall 레이아웃 적용, mall 메뉴 클릭 해결

---

src/main/java/com/project/echoproject/entity/UserCoupon.java
src/main/resources/templates/layout.html

유저쿠폰 날짜 컬럼 추가, mall 메뉴 클릭 해결

---

src/main/java/com/project/echoproject/entity/Coupon.java
src/main/resources/templates/challenge_add.html

챌린지 등록 레이아웃

---

src/main/java/com/project/echoproject/controller/NoticeController.java
src/main/java/com/project/echoproject/service/NoticeService.java
src/main/resources/templates/notice_detail.html

* 공지사항 게시글 삭제 기능추가, 디테일에 목록 버튼추가
- notice_detail.html 에 목록 버튼 추가
- NoticeController 에 게시글 삭제를 위해 questionDelete 메서드 추가
- NoticeService 에 게시글 삭제를 위해 delete 메서드 추가

hyewon_0626_2

---

src/main/resources/templates/challenge.html

챌린지 현황 레이아웃

---

src/main/java/com/project/echoproject/controller/EcoMallController.java
src/main/resources/templates/eco_mall.html
src/main/resources/templates/layout.html
src/main/resources/templates/notice_list.html

* 공지사항 레이아웃에 연결, 에코 쇼핑mall 화면 신규생성
- eco_mall.html 에코 쇼핑mall 메뉴 신규화면 생성
- EcoMallController 신규생성
- layout.html 에 메뉴명 에코 쇼핑mall으로 수정, 공지사항 메뉴 화면연결
- notice_list.html 에 layout 속성 연결 설정(공지사항 메뉴연결)

hyewon_0626_3

---

src/main/resources/templates/challenge.html

챌린지 현황 배경 흰색

---

src/main/resources/templates/notice_detail.html
src/main/resources/templates/notice_form.html

hyewon_0626_5
* 공지사항 detail 버튼수정, 게시글 작성 form 화면 레이아웃 추가
- notice_detail.html 에 a태그 -> 버튼으로 수정
- notice_form.html 화면 레이아웃 추가 및 css 추가, 취소 버튼 추가

hyewon_0626_5

---

src/main/java/com/project/echoproject/controller/MallController.java

mall 컨트롤러 변경

---

src/main/resources/templates/buy.html
src/main/resources/templates/pay.html

mall ccs 수정

---

src/main/resources/templates/error/payment_failed.html
src/main/resources/templates/mall.html

mall 홈 , 결제실패 css

---

src/main/resources/templates/notice_list.html

hyewon_0627_1
* 공지사항 게시글 list 화면 부트스트랩, css 스타일 추가 적용
- notice_list.html

hyewon_0627_1

---

src/main/resources/templates/notice_detail.html

hyewon_0627_2
* 공지사항 게시글 detail 화면 부트스트랩, css 스타일 추가 적용
- notice_detail.html

hyewon_0627_2

---

src/main/java/com/project/echoproject/controller/EcoNewsController.java
src/main/java/com/project/echoproject/service/EcoNewsService.java
src/main/resources/templates/ecoNews.html
src/main/resources/templates/layout.html

hyewon_0627_3
* 환경 알리미-[에코 뉴스 모아보기] 메뉴 네이버 뉴스 api기능 구현
- layout.html 에 에코 뉴스 모아보기 메뉴에 ecoNews 화면 연결
- ecoNews.html 신규생성
- EcoNewsController 에서 네이버 뉴스 API 기능 구현
- EcoNewsService  에서 네이버 뉴스 API 기능 구현
- 네이버 뉴스 api를 통해 '저탄소' 키워드로 게시글 10개 조회하여 보여줌

hyewon_0627_3

---

src/main/java/com/project/echoproject/controller/AdminController.java
src/main/java/com/project/echoproject/repository/ReportBoardRepository.java
src/main/java/com/project/echoproject/service/ReportBoardService.java
src/main/java/com/project/echoproject/service/ReportBoardServiceImpl.java
src/main/resources/templates/admin/report.html
src/main/resources/templates/authBoard/authBoard_detail.html

글 삭제, 신고버튼 살림

---

src/main/java/com/project/echoproject/controller/AdminController.java
src/main/java/com/project/echoproject/dto/ReportDTO.java
src/main/java/com/project/echoproject/service/AuthBoardServiceImpl.java
src/main/java/com/project/echoproject/service/SiteUserService.java
src/main/java/com/project/echoproject/service/SiteUserServiceImpl.java
src/main/resources/templates/admin/admin.html
src/main/resources/templates/admin/pointManage.html
src/main/resources/templates/admin/report.html

관리자 링크 연결, 포인트 내역

---

src/main/java/com/project/echoproject/controller/AdminController.java
src/main/java/com/project/echoproject/controller/MallController.java
src/main/resources/templates/admin/report.html

관리자 게시글 연결

---

src/main/resources/templates/cart.html

cart.html 한개 수정입니다.

---

src/main/resources/templates/admin/pointManage.html

관리자 포인트 레이아웃

---

src/main/resources/templates/challenge.html

챌린지등록 버튼 추가

---

src/main/resources/templates/admin/pointManage.html
src/main/resources/templates/admin/report.html

관리자 페이지 css

---

src/main/resources/templates/admin/pointManage.html

관리자 포인트페이지 css

---

src/main/java/com/project/echoproject/controller/AdminController.java
src/main/java/com/project/echoproject/controller/ChallengeController.java
src/main/java/com/project/echoproject/entity/Challenge.java
src/main/java/com/project/echoproject/service/ChallengeService.java
src/main/resources/templates/admin/admin.html
src/main/resources/templates/showChallenge.html

관리자 챌린지 클릭

---

src/main/resources/templates/admin/pointManage.html
src/main/resources/templates/buy.html
src/main/resources/templates/challenge_add.html

챌린지관리 페이지 수정, 결제 alert, 등록 alert

---

src/main/resources/templates/admin/pointManage.html
src/main/resources/templates/admin/report.html

관리자 메뉴 css

---

src/main/java/com/project/echoproject/controller/AdminController.java
src/main/resources/templates/admin/admin.html
src/main/resources/templates/admin/layout_admin.html
src/main/resources/templates/admin/loginFormAdmin.html
src/main/resources/templates/admin/pointManage.html
src/main/resources/templates/admin/report.html

관리자 페이지 메뉴 연결

---

src/main/resources/templates/notice_detail.html
src/main/resources/templates/notice_list.html

hyewon_0628_1
* 공지사항 admin1234 id일때 만 글작성,수정,삭제 되도록 권한 수정
- notice_list.html 에 글작성하기 버튼 ,notice_detail.html 에 수정, 삭제 버튼
로그인된 사용자이면서 id가 'admin1234' 일 때만 사용 가능하도록 권한 수정

hyewon_0628_1

---

src/main/java/com/project/echoproject/SecurityConfig.java

관리자 아니면 접근불가(오류페이지 뜸)

---

src/main/resources/templates/admin/notice_list_admin.html

hyewon_0701_1
* 관리자 메뉴에서 공지사항 화면 생성
- notice_list_admin.html 신규생성

hyewon_0701_1

---

src/main/resources/static/css/account/login.css
src/main/resources/templates/account/login.html
src/main/resources/templates/account/sign_up.html
src/main/resources/templates/order/product_detail.html

4개 수정입니다. 로그인 회원가입 html이랑 상세설명쓰기 ~!!

4개 수정입니다ㅏ.

---

src/main/resources/templates/challenge_status.html

Challenge 조금 수정이요
